default_language_version:
  python: python3

repos:
  - repo: local
    hooks:
      - id: check-validation
        name: Check validation enabled
        entry: uv run .pre-commit-scripts/check_validation.py
        language: system
        pass_filenames: false
        always_run: true
